name: 'Setup environment for build'

runs:
  using: "composite"
  steps:
    - name: Add MSBuild to PATH
      id: detect-msbuild
      uses: microsoft/setup-msbuild@v2
      with: 
        vs-version: '[15.7,)'
        
    - name: Add VSTest to Path
      id: vstest-detect
      uses: darenm/Setup-VSTest@v1.3

    - name: Add .NET 6.0
      id: dotnet-6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
