name: Tests

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'

  workflow_dispatch:
    inputs:
      configuration:
        description: "Build configuration"
        required: false
        default: "Release"

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: WorkshopTool.sln

  BUILD_CONFIGURATION: ${{ github.event.inputs.configuration || 'Release' }}
  BUILD_FRAMEWORK: net461
  MANUAL_TRIGGER: ${{ github.event.workflow != null }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Sources
      id: checkout
      with:
        fetch-depth: 0

    - uses: ./.github/actions/setup
      name: Setup Environment

    - uses: ./.github/actions/build
      name: Build Solution
      with:
        solution: ${{env.SOLUTION_FILE_PATH}}
        configuration: ${{env.BUILD_CONFIGURATION}}

    - uses: ./.github/actions/test
      name: Run Tests
      with:
        package: Tests\bin\${{env.BUILD_CONFIGURATION}}\${{env.BUILD_FRAMEWORK}}\Phoenix.WorkshopTool.Tests.dll
        settings: Tests\tests.runsettings

    - uses: ./.github/actions/changelog
      name: Generate Changelog
      with:
        project-path: Directory.Build.props

