j = j + 1

for i in range(13263):

    if caseid[i] == j:

        if taskid[i] == 'MakeTicket':

            if eventtype[i] == 'start':

                start_time = starttime[i]

            if eventtype[i] == 'complete':

                complete_time = complete[i]

print(start_time, complete_time)
